<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5OUP2NH" ignored="0" name="002_config(failed)" tests="1" failures="1" timestamp="12 Jun 2019 18:26:18 GMT" time="14.857" errors="0">
  <testcase name="runCustomTransactionNameTestCases" time="0.0" classname="driver.ConfigTest">
    <failure type="org.testng.TestNGException" message="
Data Provider public static java.lang.Object[][] utils.DataProvider.readCustomTransactionNameTestCases() returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public static java.lang.Object[][] utils.DataProvider.readCustomTransactionNameTestCases() returned a null value
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- runCustomTransactionNameTestCases -->
</testsuite> <!-- 002_config(failed) -->
